### ISSUE TITLE
Deprecation warning starting 2024.1

### ISSUE THREAD

**Issue by Alexsey** [mikinw/TabMover#11]
Hi!

Thank you for the great work done for the plugin! Starting from 2024.1 the IDE API used by TabMover is deprecated, and it triggers the warning occasionally :(

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.mnw.tabmover.actions.TabMoverActionGroup' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.mnw.tabmover]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

![Screenshot 2024-04-10 at 18 19 57](https://github.com/mikinw/TabMover/assets/6392013/9f4978a8-27e3-4069-b63d-f928ee5a4a9d)

I'm sure that all the plugin users would be grateful for the fix :)

Thank you!

**Comment by mgroth0** [comment]
Yes I am getting this too. Actually, lots of plugins are throwing this.
