### ISSUE TITLE
Cannot move tab to previous splitter in IDEA 2022.3.1

### ISSUE THREAD

**Issue by endorh** [mikinw/TabMover#3]
Hi. First of all, thank you for making this plugin.

After updating to IDEA 2022.3.1 (#IC-223.8214.52), using the `Move Tab to Previous Window/Splitter` action fails with the following error:

```
java.lang.NoSuchMethodError: 'long com.intellij.openapi.fileEditor.impl.EditorWithProviderComposite.getInitialFileTimeStamp()'
	at com.mnw.tabmover.actions.MoveTabToPreviousWindow.performAction(MoveTabToPreviousWindow.java:26)
	at com.mnw.tabmover.actions.WindowAction.actionPerformed(WindowAction.java:35)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:323)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at ...
```

Surprisingly enough, moving tabs to the *next* Window/Splitter works without issue, so I can still move them to the previous by cycling around.

**Comment by alexanderankin** [comment]
<details><summary>here is the full stack trace i got:</summary>

```
java.lang.NoSuchMethodError: 'long com.intellij.openapi.fileEditor.impl.EditorWithProviderComposite.getInitialFileTimeStamp()'
	at com.mnw.tabmover.actions.MoveTabToPreviousWindow.performAction(MoveTabToPreviousWindow.java:26)
	at com.mnw.tabmover.actions.WindowAction.actionPerformed(WindowAction.java:35)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:323)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:584)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:346)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:703)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:647)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:478)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:467)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:815)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

</details>

**Comment by mikinw** [comment]
I have seen the deprecation warning coming from jetbrains, but at the moment I have limited time to figure out how to update the plugin. I try to make an update someday. 
(Especially because seeing people using it makes me somewhat happy :-) )

**Comment by alexanderankin** [comment]
not this function, but overall the plugin is fairly critical to my workflow so i might also play around with that and see

**Comment by alexanderankin** [comment]
I haven't tried to actually test the implementation but I've removed the code that I think was causing the problem (it wouldn't compile due to the import statement for a non-existent class: `import com.mnw.tabmover.TabMoverAppComponent;` and then also I set the intellij version in `build.gradle.kts` to 2022.3 instead of 2019 and the method `getInitialFileTimeStamp` turned fully red because it was not found (as the runtime error suggests) - but it was a simple getter so I'm not sure what purpose it served (maybe experimentation?)).

the changes are here: alexanderankin/TabMover#1

**Comment by alexanderankin** [comment]
Also I'm not sure how far backwards compatible you want to go @mikinw - I was thinking that since all these methods are deprecated, you might want to rewrite using the replacement APIs and try catch on Method/ClassNotFound - and call the old methods with reflection. or just remove support for older intellij versions?

**Comment by mikinw** [comment]
@alexanderankin thank you for the continuous interest.
Indeed that deprecated method was not used (it was a remnant of feature I wanted to add, but I didn't implement it). 
I've updated the plugin. It took more time to adapt to the new build tool chain. :-/
Please feel free to reach out if the behaviour is not as expected, I didn't test it fully.
(jetbrains is reviewing the update. It should be done within 2 days)
